sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-7 g++-7

script:
  - gcc-7 --version
  - mkdir -p builddir
  - cd builddir
  - cmake ..
  - make

