sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - gcc-7
      - g++-7
      - clang-6.0
      - libstdc++6

script:
  - mkdir -p builddir
  - cd builddir
  - CC=clang-6.0 && CXX=clang-6.0 cmake ..
  - make
