language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-7
      - libc++-7-dev
      - libc++abi-7-dev

script:
  - sh .travis/script.sh

env:
  global:
    secure: a9Tx4hIUmfq3LaFn3glqxpKMsJlLb4ESxbepNImNPywbwEj3YqCTARhjk+Le5rg0QE0Js50crukhPWYqVEtX5yCp6Es3VZ5Fu7uXD46I6G73nQIuPipofxCisBZt8WLWzz/y0jZlyz+mjEKrh6W6fsC36lGF2zlH/4Ph0oq9GCg=
