steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/xapiand:${TAG_NAME}', 'contrib/docker/xapiand' ]
images:
- 'gcr.io/${PROJECT_ID}/xapiand:${TAG_NAME}'
timeout: 1h
